@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class ConsoleUI {
Sodoku sudoku


+start()
-afficherGrille()
}

class GUI {

}

GUI --> Sudoku
ConsoleUI --> Sudoku
ConsoleUI ..> Case

Class Sudoku {

}

Sudoku --> Grille
Sudoku --> Solveur

class Solveur {
-Grille grille

+boolean solve()
List<Integer> trouverCandidats(int row, int col)
}

Solveur .> Grille


class Grille {
-Case[][] grille
-Bloc[] blocs
-int taille

Case[][] getGrille()
boolean isValid()
}

Grille o-- Case
Grille o-- Bloc

class Bloc {
Case[] cases
}


class Case {
int idBloc
Integer valeur
// boolean fixed
}

@enduml
