@startuml
left to right direction
actor User

package Sudoku {
usecase "Rentrer une grille manuellement" as RentrerGrille
usecase "générer une grille " as GenererGrille
usecase "Afficher la grille" as AfficherGrille
usecase "Résoudre la grille" as ResoudreGrille
usecase "Choisir le/les méthodes de résolution" as choixmeth
usecase "Choix de diffculté" as Choixdifficulté
usecase "Afficher suite d'opération de résolution" as afflog
usecase "resolvable ?" as resolvable

GenererGrille .> resolvable : <<include>>
User -- GenererGrille
User -- afflog
GenererGrille ..> Choixdifficulté : <<include>>
User -- RentrerGrille

User-- AfficherGrille
User-- ResoudreGrille
ResoudreGrille ..> choixmeth : <<include>>


}
@enduml
