@startuml
'https://plantuml.com/sequence-diagram

autonumber
activate user
activate ConsoleGUI


user <- ConsoleGUI : choix d'action
user --> ConsoleGUI : Réponse d'action
alt Choix == 1
    user -> ConsoleGUI: Select create sudoku
    user <-- ConsoleGUI : demande taille sudoku
    user ->ConsoleGUI :
else Choix == 2
    loop
    user <-- ConsoleGUI : demande méthode de resolutions
    user -> ConsoleGUI: méthode choisie
       alt  choix méthode = 1

       ConsoleGUI   <- ConsoleGUI : ajoute elemination_direct à l'ensemble  de résolution
       else choix méthode== 2
        ConsoleGUI   <- ConsoleGUI : ajoute placement_force à l'ensemble  de résolution
       else choix méthode== 3
       ConsoleGUI   <- ConsoleGUI : ajoute Paires à l'ensemble  de résolution



       else choix méthode== 4
       ConsoleGUI   <- ConsoleGUI : ajoute BackTracking à l'ensemble  de résolution

       else choix méthode== 5

            ConsoleGUI -> Sudoku : solve avec l'ensemble méthode
            activate Sudoku
            Sudoku -> Solveur : resolutions
            activate Solveur
            Solveur -> Solveur : solve regle
            alt backtracking actif
                Solveur -> Solveur : solvebacktracking
            end
                Solveur -> Solveur : Résout avec le/les règles choisie


                Solveur -> Grille : isComplet()
                activate  Grille
                loop pour chaque case
                Grille -> Case : get valeur case
                Grille <-- Case : valeur de case
                end
                Solveur <-- Grille : renvoie de isComplet()
                deactivate Grille
                Sudoku  <-- Solveur : résultats résolution
                deactivate Solveur
                ConsoleGUI <-- Sudoku : résultats
                deactivate Sudoku
                user <-- ConsoleGUI : resultats solve



            deactivate Sudoku

        end
       end
else Choix == 3
    user <-- ConsoleGUI : afficher le sudoku
else Choix == 4
    user <-- ConsoleGUI:  la suite des opérations de résolution

else Choix == 5
    user <- ConsoleGUI : demande taille à générer
    user --> ConsoleGUI : taille
    user <- ConsoleGUI : demande difficulté générer
    user --> ConsoleGUI : difficulté
    ConsoleGUI -> Sudoku : générer en fonction de la difficulté sélèctionée

    activate Sudoku
    Sudoku -> Grille : create grille
    activate Grille
    Sudoku <-- Grille : grille créer
    deactivate Grille
    Sudoku -> Solveur : vérifie grille solvable
    activate Solveur
    Sudoku <-- Solveur : grille verifier sol
    deactivate Solveur

    ConsoleGUI <- Sudoku : sudoku solvable










else



end //endloop

@enduml